name: thoth-chat

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: thoth-chat:local
    container_name: thoth-chat-app

    ports:
      - "8080:8080"

    environment:
      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - app_storage:/app/storage
      - app_data:/app/data
      - ./config.yaml:/app/config.yaml:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - thoth-chat

volumes:
  app_storage:
    name: thoth-chat-app-storage

  app_data:
    name: thoth-chat-app-data

networks:
  thoth-chat:
    name: thoth-chat-network